name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jekyll-site
          path: _site
          retention-days: 1
